author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: STARTUP

commands:
  debug:
    description: Debug Command
    usage: |
      /<command> [enable|disable] <nodeName>
  updater:
    description: Updater Command
    aliases: [update]
    usage: |
      /<command> status|check <nodeName>|all
      /<command> download|dl <nodeName>