author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

softdepend: [NWorld]

commands:
  nenchantingegg:
    description: Main plugin command
    aliases: [nee]
    usage: |
      /<command> reload messages