name: NEnchantingEgg
version: 0.4.0
description: EnchantingEgg plugin for N plugin suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.nenchantingegg.NEnchantingEgg

load: POSTWORLD

depend: [NCore]