author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]
softdepend: [NWorld]

commands:
  npermissions:
    description: Main plugin command
    aliases: [permissions, nperms, perms, nperm, perm]
    usage: |
      /<command> reload <messages|groups|players>
  setgroup:
    description: Change the main group of a player
    aliases: [setg]
    usage: |
      /<command> <playerName|UUID>[,...] <groupName> [force]