author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

commands:
  nend:
    description: Base NTheEndAgain command
    aliases: [end,ntheendagain]
    usage: |
      /<command> help
