name: NTheEndAgain
version: maven-version-number
description: End plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.ntheendagain.NTheEndAgain

load: POSTWORLD

depend: [NCore]

commands:
  nend:
    description: Base NTheEndAgain command
    aliases: [end,ntheendagain]
