name: NWorld
version: 0.3.2
description: World handling plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr/
main: fr.ribesg.bukkit.nworld.NWorld

load: POSTWORLD

softdepend: [NCore]

commands:
  nworld:
    description: Main command
    aliases: [nw,world]
    usage: |
      /<command> [worldName]
      /<command> create <worldName> [seed] [requiredPermission] [hidden]
      /<command> load|unload <worldName>
      /<command> setHidden|setPerm|setNether|setEnd <worldName> <value>
  spawn:
    description: Spawn command
    usage: |
      /<command>
  setspawn:
    description: Set the spawn
    usage: |
      /<command>
  warp:
    description: Warp to a point
    usage: |
      /<command> [warpName]
      /<command> <setHidden|setPerm> <warpName> <value>
  setwarp:
    description: Place / Move a Warp
    usage: |
      /<command> <warpName> -- Move a Warp
      /<command> <warpName> [requiredPermission] [hidden] -- Place a Warp
  delwarp:
    description: Remove a Warp
    usage: |
      /<command> <warpName>
