name: NCuboid
version: 0.1.0
description: Cuboid plugin for N plugin suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.ncuboid.NCuboid

load: POSTWORLD

softdepend: [NCore,NWorld]

commands:
    cuboid:
        description: General cuboid command
        aliases: [c,cubo]
        permission: ncuboid.cmd.general
        usage: |
            §c/<command> help
