name: NTheEndAgain
version: 0.1.1
description: End plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.ntheendagain.NTheEndAgain

load: POSTWORLD

softdepend: [NCore]

commands:
  end:
    description: Base NTheEndAgain command
