name: NTheEndAgain
version: 0.0.5
description: End plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.ntheendagain.NTheEndAgain

load: POSTWORLD

depend: [NCore]

commands:
  end:
    description: Base NTheEndAgain command