author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

load: POSTWORLD

depend: [NCore]
softdepend: [NWorld]

commands:
    cuboid:
        description: General cuboid command
        aliases: [c,cubo]
        permission: ncuboid.cmd.general
        usage: |
            §c/<command> help
