author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]
softdepend: [NWorld, dynmap]

commands:
    cuboid:
        description: General cuboid command
        aliases: [c,cubo]
        usage: |
            /<command> help