author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

commands:
  nworld:
    description: Main command
    aliases: [nw,world]
    usage: |
      /<command> [worldName]
      /<command> create <worldName> [seed] [requiredPermission] [hidden] [type]
      /<command> load|unload <worldName>
      /<command> setHidden|setPerm|setNether|setEnd <worldName> <value>
  spawn:
    description: Spawn command
    usage: |
      /<command>
  setspawn:
    description: Set the spawn
    usage: |
      /<command>
  warp:
    description: Warp to a point
    usage: |
      /<command> [warpName]
      /<command> <setHidden|setPerm> <warpName> <value>
  setwarp:
    description: Place / Move a Warp
    usage: |
      /<command> <warpName> -- Move a Warp
      /<command> <warpName> [requiredPermission] [hidden] -- Place a Warp
  delwarp:
    description: Remove a Warp
    usage: |
      /<command> <warpName>
