author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

load: POSTWORLD

depend: [NCore]

commands:
  pm:
    description: Private message
    aliases: [m,msg]
    usage: |
      /<command>
  pr:
    description: Respond to latest PM
    aliases: [r]
    usage: |
      /<command>
  nick:
    description: Nickname
    usage: |
      /<command> <realName> <nickName>
