author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

commands:
  ntalk:
    description: Main plugin command
    usage: |
      /<command> reload messages
  pm:
    description: Private message
    aliases: [m,msg]
    usage: |
      /<command>
  pr:
    description: Respond to latest PM
    aliases: [r]
    usage: |
      /<command>
  nick:
    description: Nickname
    usage: |
      /<command> <realName> <nickName>
