name: NTalk
version: 0.4.0
description: Chat plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr/
main: fr.ribesg.bukkit.ntalk.NTalk

load: POSTWORLD

depend: [NCore]

commands:
  pm:
    description: Private message
    aliases: [m,msg]
    usage: |
      /<command>
  pr:
    description: Respond to latest PM
    aliases: [r]
    usage: |
      /<command>
  nick:
    description: Nickname
    usage: |
      /<command> <realName> <nickName>
