name: NPlayer
version: 0.3.0
description: Player plugin for N plugins suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.nplayer.NPlayer

load: POSTWORLD

softdepend: [NCore]

commands:
  login:
    description: Login command
  register:
    description: Register command
  logout:
    description: Logout command
  info:
    description: Info command
  home:
    description: Home command
  sethome:
    description: SetHome command