name: NGeneral
version: 0.4.0
description: General commands
author: Ribesg
website: http://www.ribesg.fr/
main: fr.ribesg.bukkit.ngeneral.NGeneral

load: POSTWORLD

depend: [NCore]

commands:
  god:
    description: GodMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  fly:
    description: FlyMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  flyspeed:
    description: Fly Speed Command
    aliases: [flys]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  walkspeed:
    description: Walk Speed Command
    aliases: [walks]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  afk:
    description: Afk Command
    usage: |
      /<command> [Reason]
  time:
    description: Time Command
    usage: |
      /<command> <"day"|"night"|value> [world]
  weather:
    description: Weather Command
    usage: |
      /<command> <"clear"|"rain"|"thunder"> [duration] [world]