author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

load: POSTWORLD

depend: [NCore]

commands:
  god:
    description: GodMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  fly:
    description: FlyMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  flyspeed:
    description: Fly Speed Command
    aliases: [flys]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  walkspeed:
    description: Walk Speed Command
    aliases: [walks]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  afk:
    description: Afk Command
    usage: |
      /<command> [Reason]
  time:
    description: Time Command
    aliases: [t]
    usage: |
      /<command> <"d"|"day"|"n"|"night"|value> [world]
  weather:
    description: Weather Command
    aliases: [w]
    usage: |
      /<command> <"c"|"clear"|"r"|"rain"|"t"|"thunder"> [duration] [world]