author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

load: POSTWORLD

depend: [NCore]

commands:
  god:
    description: GodMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  fly:
    description: FlyMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  flyspeed:
    description: Fly Speed Command
    aliases: [flys]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  walkspeed:
    description: Walk Speed Command
    aliases: [walks]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  afk:
    description: Afk Command
    usage: |
      /<command> [Reason]
  time:
    description: Time Command
    aliases: [t]
    usage: |
      /<command> <"d"|"day"|"n"|"night"|value> [world]
  weather:
    description: Weather Command
    aliases: [w]
    usage: |
      /<command> <"c"|"clear"|"r"|"rain"|"t"|"thunder"> [duration] [world]
  tp:
    description: Teleport Command
    usage: |
      /<command> [playerName[,...]] <playerName>
  tppos:
    description: Teleport Command
    aliases: [tpp]
    usage: |
      /<command> [playerName[,...]] <x y z>|<x;y;z>
  tphere:
    description: Teleport Command
    aliases: [tph]
    usage: |
      /<command> <playerName[,...]>
  tpthere:
    description: Teleport Command
    aliases: [tpt]
    usage: |
      /<command> [playerName[,...]]
  tpback:
    description: Teleport Command
    aliases: [tpb]
    usage: |
      /<command> [playerName[,...]]
  itemnetwork:
    description: ItemNetwork Command
    aliases: [in]
    usage: |
      /<command> <create|delete> <networkName>