author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]
softdepend: [dynmap]

commands:
  ngeneral:
    description: Main plugin command
    usage: |
      /<command> reload messages
  god:
    description: GodMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  fly:
    description: FlyMode Command
    usage: |
      /<command> [enable|disable] [playerName[,...]]
  flyspeed:
    description: Fly Speed Command
    aliases: [flys]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  walkspeed:
    description: Walk Speed Command
    aliases: [walks]
    usage: |
      /<command> <-1...1>|<reset> [playerName[,...]]
  afk:
    description: Afk Command
    usage: |
      /<command> [Reason]
  busy:
    description: Busy Command
    usage: |
      /<command> [Reason]
  time:
    description: Time Command
    aliases: [t]
    usage: |
      /<command> <"d"|"day"|"n"|"night"|value> [world]
  weather:
    description: Weather Command
    aliases: [w]
    usage: |
      /<command> <"c"|"clear"|"r"|"rain"|"t"|"thunder"> [duration] [world]
  repair:
    description: Repair Command
    usage: |
      /<command>
  nightvision:
    description: Night Vision Command
    aliases: [nv]
    usage: |
      /<command>
  tp:
    description: Teleport Command
    usage: |
      /<command> [playerName[,...]] <playerName>
  tppos:
    description: Teleport Command
    aliases: [tpp]
    usage: |
      /<command> [playerName[,...]] <x y z>|<x;y;z>
  tphere:
    description: Teleport Command
    aliases: [tph]
    usage: |
      /<command> <playerName[,...]>
  tpthere:
    description: Teleport Command
    aliases: [tpt]
    usage: |
      /<command> [playerName[,...]]
  tpworld:
    description: Teleport Command
    aliases: [tpw]
    usage: |
      /<command> [playerName[,...]] <worldName>
  tpback:
    description: Teleport Command
    aliases: [tpb]
    usage: |
      /<command> [playerName[,...]]
  itemnetwork:
    description: ItemNetwork Command
    aliases: [in]
    usage: |
      /<command> <create|delete> <networkName>
  heal:
    description: Heal Command
    usage: |
      /<command> [playerName[,...][ ...]]
  feed:
    description: Feed Command
    usage: |
      /<command> [playerName[,...][ ...]]
  health:
    description: Health Command
    usage: |
      /<command> [playerName[,...][ ...]] <value>
  food:
    description: Food Command
    usage: |
      /<command> [playerName[,...][ ...]] <value>
  spy:
    description: Spy Command
    usage: |
      /<command> [playerName]

permissions:

  ngeneral.admin:
    description: NGeneral plugin admin
    default: false
    children:
      ngeneral.user: true

      ngeneral.cmd.reload:
         default: false
      ngeneral.cmd.god:
         default: false
      ngeneral.cmd.god.others:
         default: false
      ngeneral.cmd.fly:
         default: false
      ngeneral.cmd.fly.others:
         default: false
      ngeneral.cmd.flyspeed:
         default: false
      ngeneral.cmd.flyspeed.others:
         default: false
      ngeneral.cmd.walkspeed:
         default: false
      ngeneral.cmd.walkspeed.others:
         default: false
      ngeneral.cmd.time:
         default: false
      ngeneral.cmd.weather:
         default: false
      ngeneral.cmd.repair:
         default: false
      ngeneral.cmd.nightvision:
         default: false
      ngeneral.cmd.itemnetwork.all:
         default: false
      ngeneral.cmd.spy:
         default: false
      ngeneral.cmd.tp:
         default: false
      ngeneral.cmd.tppos:
         default: false
      ngeneral.cmd.tphere:
         default: false
      ngeneral.cmd.tpthere:
         default: false
      ngeneral.cmd.tpworld:
         default: false
      ngeneral.cmd.tpback:
         default: false
      ngeneral.cmd.heal:
         default: false
      ngeneral.cmd.health:
         default: false
      ngeneral.cmd.feed:
         default: false
      ngeneral.cmd.food:
         default: false

      ngeneral.protectionsign.bypass:
         default: false
      ngeneral.protectionsign.break:
         default: false

  ngeneral.user:
    description: NGeneral plugin admin
    default: false
    children:

      ngeneral.cmd.afk:
         default: false
      ngeneral.cmd.busy:
         default: false
      ngeneral.cmd.itemnetwork:
         default: false

      ngeneral.protectionsign:
         default: false
      ngeneral.signcolors:
         default: false
